name: hello-world
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'A sample input for the workflow'
        required: false
        default: 'default value'
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
